import type { AvatarConfig } from "../src/lib/avatar";

// AJ's current local profile avatar. Keep this independent of the seeded username
// so a fresh seed restores the same picture even when the name changes.
export const seedAjAvatar: AvatarConfig = {
  avatarStyle: "lorelei",
  skinColor: "ffe4c7",
  top: "shortFlat",
  hairColor: "161616",
  eyes: "happy",
  eyebrows: "raisedExcitedNatural",
  mouth: "tongue",
  clothing: "shirtVNeck",
  clothesColor: "3c4f5c",
  clothingGraphic: "pizza",
  facialHair: "none",
  facialHairColor: "2c1b18",
  accessories: "none",
  accessoriesColor: "262e33",
  hatColor: "78350f",
  backgroundColor: "ff488e",
  backgroundAccent: "ffffff",
  backgroundType: "gradientLinear",
  backgroundRotation: "135",
  framing: "default",
  mirror: "normal",
  scale: "120",
  adventurerHair: "short01",
  adventurerEyes: "variant01",
  adventurerEyebrows: "variant01",
  adventurerMouth: "variant01",
  adventurerFeature: "none",
  adventurerGlasses: "none",
  adventurerEarrings: "none",
  loreleiHair: "variant41",
  loreleiEyes: "variant21",
  loreleiEyebrows: "variant07",
  loreleiMouth: "happy03",
  loreleiHead: "variant04",
  loreleiNose: "variant01",
  loreleiGlasses: "variant01",
  loreleiEarrings: "none",
  loreleiBeard: "none",
  loreleiFreckles: "freckles",
  loreleiHairAccessories: "flowers",
};
