/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FeedRouteImport } from './routes/feed'
import { Route as BillsRouteImport } from './routes/bills'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PartiesIndexRouteImport } from './routes/parties/index'
import { Route as PartiesCreateRouteImport } from './routes/parties/create'
import { Route as PartiesIdRouteImport } from './routes/parties/$id'
import { Route as ApiGameAdvanceRouteImport } from './routes/api/game-advance'
import { Route as PartiesMergeIdRouteImport } from './routes/parties/merge/$id'
import { Route as PartiesManageIdRouteImport } from './routes/parties/manage/$id'
import { Route as ApiFeedListRouteImport } from './routes/api/feed.list'
import { Route as ApiFeedAddRouteImport } from './routes/api/feed.add'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedRoute = FeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const BillsRoute = BillsRouteImport.update({
  id: '/bills',
  path: '/bills',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PartiesIndexRoute = PartiesIndexRouteImport.update({
  id: '/parties/',
  path: '/parties/',
  getParentRoute: () => rootRouteImport,
} as any)
const PartiesCreateRoute = PartiesCreateRouteImport.update({
  id: '/parties/create',
  path: '/parties/create',
  getParentRoute: () => rootRouteImport,
} as any)
const PartiesIdRoute = PartiesIdRouteImport.update({
  id: '/parties/$id',
  path: '/parties/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGameAdvanceRoute = ApiGameAdvanceRouteImport.update({
  id: '/api/game-advance',
  path: '/api/game-advance',
  getParentRoute: () => rootRouteImport,
} as any)
const PartiesMergeIdRoute = PartiesMergeIdRouteImport.update({
  id: '/parties/merge/$id',
  path: '/parties/merge/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PartiesManageIdRoute = PartiesManageIdRouteImport.update({
  id: '/parties/manage/$id',
  path: '/parties/manage/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFeedListRoute = ApiFeedListRouteImport.update({
  id: '/api/feed/list',
  path: '/api/feed/list',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFeedAddRoute = ApiFeedAddRouteImport.update({
  id: '/api/feed/add',
  path: '/api/feed/add',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bills': typeof BillsRoute
  '/feed': typeof FeedRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
  '/api/game-advance': typeof ApiGameAdvanceRoute
  '/parties/$id': typeof PartiesIdRoute
  '/parties/create': typeof PartiesCreateRoute
  '/parties': typeof PartiesIndexRoute
  '/api/feed/add': typeof ApiFeedAddRoute
  '/api/feed/list': typeof ApiFeedListRoute
  '/parties/manage/$id': typeof PartiesManageIdRoute
  '/parties/merge/$id': typeof PartiesMergeIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bills': typeof BillsRoute
  '/feed': typeof FeedRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
  '/api/game-advance': typeof ApiGameAdvanceRoute
  '/parties/$id': typeof PartiesIdRoute
  '/parties/create': typeof PartiesCreateRoute
  '/parties': typeof PartiesIndexRoute
  '/api/feed/add': typeof ApiFeedAddRoute
  '/api/feed/list': typeof ApiFeedListRoute
  '/parties/manage/$id': typeof PartiesManageIdRoute
  '/parties/merge/$id': typeof PartiesMergeIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bills': typeof BillsRoute
  '/feed': typeof FeedRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
  '/api/game-advance': typeof ApiGameAdvanceRoute
  '/parties/$id': typeof PartiesIdRoute
  '/parties/create': typeof PartiesCreateRoute
  '/parties/': typeof PartiesIndexRoute
  '/api/feed/add': typeof ApiFeedAddRoute
  '/api/feed/list': typeof ApiFeedListRoute
  '/parties/manage/$id': typeof PartiesManageIdRoute
  '/parties/merge/$id': typeof PartiesMergeIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bills'
    | '/feed'
    | '/login'
    | '/profile'
    | '/signup'
    | '/api/game-advance'
    | '/parties/$id'
    | '/parties/create'
    | '/parties'
    | '/api/feed/add'
    | '/api/feed/list'
    | '/parties/manage/$id'
    | '/parties/merge/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bills'
    | '/feed'
    | '/login'
    | '/profile'
    | '/signup'
    | '/api/game-advance'
    | '/parties/$id'
    | '/parties/create'
    | '/parties'
    | '/api/feed/add'
    | '/api/feed/list'
    | '/parties/manage/$id'
    | '/parties/merge/$id'
  id:
    | '__root__'
    | '/'
    | '/bills'
    | '/feed'
    | '/login'
    | '/profile'
    | '/signup'
    | '/api/game-advance'
    | '/parties/$id'
    | '/parties/create'
    | '/parties/'
    | '/api/feed/add'
    | '/api/feed/list'
    | '/parties/manage/$id'
    | '/parties/merge/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BillsRoute: typeof BillsRoute
  FeedRoute: typeof FeedRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  SignupRoute: typeof SignupRoute
  ApiGameAdvanceRoute: typeof ApiGameAdvanceRoute
  PartiesIdRoute: typeof PartiesIdRoute
  PartiesCreateRoute: typeof PartiesCreateRoute
  PartiesIndexRoute: typeof PartiesIndexRoute
  ApiFeedAddRoute: typeof ApiFeedAddRoute
  ApiFeedListRoute: typeof ApiFeedListRoute
  PartiesManageIdRoute: typeof PartiesManageIdRoute
  PartiesMergeIdRoute: typeof PartiesMergeIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed': {
      id: '/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof FeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bills': {
      id: '/bills'
      path: '/bills'
      fullPath: '/bills'
      preLoaderRoute: typeof BillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parties/': {
      id: '/parties/'
      path: '/parties'
      fullPath: '/parties'
      preLoaderRoute: typeof PartiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parties/create': {
      id: '/parties/create'
      path: '/parties/create'
      fullPath: '/parties/create'
      preLoaderRoute: typeof PartiesCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parties/$id': {
      id: '/parties/$id'
      path: '/parties/$id'
      fullPath: '/parties/$id'
      preLoaderRoute: typeof PartiesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/game-advance': {
      id: '/api/game-advance'
      path: '/api/game-advance'
      fullPath: '/api/game-advance'
      preLoaderRoute: typeof ApiGameAdvanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parties/merge/$id': {
      id: '/parties/merge/$id'
      path: '/parties/merge/$id'
      fullPath: '/parties/merge/$id'
      preLoaderRoute: typeof PartiesMergeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parties/manage/$id': {
      id: '/parties/manage/$id'
      path: '/parties/manage/$id'
      fullPath: '/parties/manage/$id'
      preLoaderRoute: typeof PartiesManageIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/feed/list': {
      id: '/api/feed/list'
      path: '/api/feed/list'
      fullPath: '/api/feed/list'
      preLoaderRoute: typeof ApiFeedListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/feed/add': {
      id: '/api/feed/add'
      path: '/api/feed/add'
      fullPath: '/api/feed/add'
      preLoaderRoute: typeof ApiFeedAddRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BillsRoute: BillsRoute,
  FeedRoute: FeedRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  SignupRoute: SignupRoute,
  ApiGameAdvanceRoute: ApiGameAdvanceRoute,
  PartiesIdRoute: PartiesIdRoute,
  PartiesCreateRoute: PartiesCreateRoute,
  PartiesIndexRoute: PartiesIndexRoute,
  ApiFeedAddRoute: ApiFeedAddRoute,
  ApiFeedListRoute: ApiFeedListRoute,
  PartiesManageIdRoute: PartiesManageIdRoute,
  PartiesMergeIdRoute: PartiesMergeIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
