/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SearchRouteImport } from './routes/search'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FeedRouteImport } from './routes/feed'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProfileIndexRouteImport } from './routes/profile/index'
import { Route as PartiesIndexRouteImport } from './routes/parties/index'
import { Route as BillsIndexRouteImport } from './routes/bills/index'
import { Route as BankIndexRouteImport } from './routes/bank/index'
import { Route as ProfileIdRouteImport } from './routes/profile/$id'
import { Route as PartiesCreateRouteImport } from './routes/parties/create'
import { Route as PartiesIdRouteImport } from './routes/parties/$id'
import { Route as ElectionsSenateRouteImport } from './routes/elections/senate'
import { Route as ElectionsPresidentRouteImport } from './routes/elections/president'
import { Route as ElectionsCampaignRouteImport } from './routes/elections/campaign'
import { Route as BillsSenateRouteImport } from './routes/bills/senate'
import { Route as BillsOvalOfficeRouteImport } from './routes/bills/oval-office'
import { Route as BillsHouseOfRepresentativesRouteImport } from './routes/bills/house-of-representatives'
import { Route as BillsCreateRouteImport } from './routes/bills/create'
import { Route as BillsIdRouteImport } from './routes/bills/$id'
import { Route as BankCreateRouteImport } from './routes/bank/create'
import { Route as ApiHourlyAdvanceRouteImport } from './routes/api/hourly-advance'
import { Route as ApiGameAdvanceRouteImport } from './routes/api/game-advance'
import { Route as ApiBotRouteImport } from './routes/api/bot'
import { Route as ApiBillAdvanceRouteImport } from './routes/api/bill-advance'
import { Route as PartiesMergeIdRouteImport } from './routes/parties/merge/$id'
import { Route as PartiesManageIdRouteImport } from './routes/parties/manage/$id'
import { Route as BillsEditIdRouteImport } from './routes/bills/edit/$id'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedRoute = FeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => rootRouteImport,
} as any)
const PartiesIndexRoute = PartiesIndexRouteImport.update({
  id: '/parties/',
  path: '/parties/',
  getParentRoute: () => rootRouteImport,
} as any)
const BillsIndexRoute = BillsIndexRouteImport.update({
  id: '/bills/',
  path: '/bills/',
  getParentRoute: () => rootRouteImport,
} as any)
const BankIndexRoute = BankIndexRouteImport.update({
  id: '/bank/',
  path: '/bank/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIdRoute = ProfileIdRouteImport.update({
  id: '/profile/$id',
  path: '/profile/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PartiesCreateRoute = PartiesCreateRouteImport.update({
  id: '/parties/create',
  path: '/parties/create',
  getParentRoute: () => rootRouteImport,
} as any)
const PartiesIdRoute = PartiesIdRouteImport.update({
  id: '/parties/$id',
  path: '/parties/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ElectionsSenateRoute = ElectionsSenateRouteImport.update({
  id: '/elections/senate',
  path: '/elections/senate',
  getParentRoute: () => rootRouteImport,
} as any)
const ElectionsPresidentRoute = ElectionsPresidentRouteImport.update({
  id: '/elections/president',
  path: '/elections/president',
  getParentRoute: () => rootRouteImport,
} as any)
const ElectionsCampaignRoute = ElectionsCampaignRouteImport.update({
  id: '/elections/campaign',
  path: '/elections/campaign',
  getParentRoute: () => rootRouteImport,
} as any)
const BillsSenateRoute = BillsSenateRouteImport.update({
  id: '/bills/senate',
  path: '/bills/senate',
  getParentRoute: () => rootRouteImport,
} as any)
const BillsOvalOfficeRoute = BillsOvalOfficeRouteImport.update({
  id: '/bills/oval-office',
  path: '/bills/oval-office',
  getParentRoute: () => rootRouteImport,
} as any)
const BillsHouseOfRepresentativesRoute =
  BillsHouseOfRepresentativesRouteImport.update({
    id: '/bills/house-of-representatives',
    path: '/bills/house-of-representatives',
    getParentRoute: () => rootRouteImport,
  } as any)
const BillsCreateRoute = BillsCreateRouteImport.update({
  id: '/bills/create',
  path: '/bills/create',
  getParentRoute: () => rootRouteImport,
} as any)
const BillsIdRoute = BillsIdRouteImport.update({
  id: '/bills/$id',
  path: '/bills/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BankCreateRoute = BankCreateRouteImport.update({
  id: '/bank/create',
  path: '/bank/create',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHourlyAdvanceRoute = ApiHourlyAdvanceRouteImport.update({
  id: '/api/hourly-advance',
  path: '/api/hourly-advance',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGameAdvanceRoute = ApiGameAdvanceRouteImport.update({
  id: '/api/game-advance',
  path: '/api/game-advance',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBotRoute = ApiBotRouteImport.update({
  id: '/api/bot',
  path: '/api/bot',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBillAdvanceRoute = ApiBillAdvanceRouteImport.update({
  id: '/api/bill-advance',
  path: '/api/bill-advance',
  getParentRoute: () => rootRouteImport,
} as any)
const PartiesMergeIdRoute = PartiesMergeIdRouteImport.update({
  id: '/parties/merge/$id',
  path: '/parties/merge/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PartiesManageIdRoute = PartiesManageIdRouteImport.update({
  id: '/parties/manage/$id',
  path: '/parties/manage/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BillsEditIdRoute = BillsEditIdRouteImport.update({
  id: '/bills/edit/$id',
  path: '/bills/edit/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/calendar': typeof CalendarRoute
  '/feed': typeof FeedRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/api/bill-advance': typeof ApiBillAdvanceRoute
  '/api/bot': typeof ApiBotRoute
  '/api/game-advance': typeof ApiGameAdvanceRoute
  '/api/hourly-advance': typeof ApiHourlyAdvanceRoute
  '/bank/create': typeof BankCreateRoute
  '/bills/$id': typeof BillsIdRoute
  '/bills/create': typeof BillsCreateRoute
  '/bills/house-of-representatives': typeof BillsHouseOfRepresentativesRoute
  '/bills/oval-office': typeof BillsOvalOfficeRoute
  '/bills/senate': typeof BillsSenateRoute
  '/elections/campaign': typeof ElectionsCampaignRoute
  '/elections/president': typeof ElectionsPresidentRoute
  '/elections/senate': typeof ElectionsSenateRoute
  '/parties/$id': typeof PartiesIdRoute
  '/parties/create': typeof PartiesCreateRoute
  '/profile/$id': typeof ProfileIdRoute
  '/bank': typeof BankIndexRoute
  '/bills': typeof BillsIndexRoute
  '/parties': typeof PartiesIndexRoute
  '/profile': typeof ProfileIndexRoute
  '/bills/edit/$id': typeof BillsEditIdRoute
  '/parties/manage/$id': typeof PartiesManageIdRoute
  '/parties/merge/$id': typeof PartiesMergeIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/calendar': typeof CalendarRoute
  '/feed': typeof FeedRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/api/bill-advance': typeof ApiBillAdvanceRoute
  '/api/bot': typeof ApiBotRoute
  '/api/game-advance': typeof ApiGameAdvanceRoute
  '/api/hourly-advance': typeof ApiHourlyAdvanceRoute
  '/bank/create': typeof BankCreateRoute
  '/bills/$id': typeof BillsIdRoute
  '/bills/create': typeof BillsCreateRoute
  '/bills/house-of-representatives': typeof BillsHouseOfRepresentativesRoute
  '/bills/oval-office': typeof BillsOvalOfficeRoute
  '/bills/senate': typeof BillsSenateRoute
  '/elections/campaign': typeof ElectionsCampaignRoute
  '/elections/president': typeof ElectionsPresidentRoute
  '/elections/senate': typeof ElectionsSenateRoute
  '/parties/$id': typeof PartiesIdRoute
  '/parties/create': typeof PartiesCreateRoute
  '/profile/$id': typeof ProfileIdRoute
  '/bank': typeof BankIndexRoute
  '/bills': typeof BillsIndexRoute
  '/parties': typeof PartiesIndexRoute
  '/profile': typeof ProfileIndexRoute
  '/bills/edit/$id': typeof BillsEditIdRoute
  '/parties/manage/$id': typeof PartiesManageIdRoute
  '/parties/merge/$id': typeof PartiesMergeIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/calendar': typeof CalendarRoute
  '/feed': typeof FeedRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/api/bill-advance': typeof ApiBillAdvanceRoute
  '/api/bot': typeof ApiBotRoute
  '/api/game-advance': typeof ApiGameAdvanceRoute
  '/api/hourly-advance': typeof ApiHourlyAdvanceRoute
  '/bank/create': typeof BankCreateRoute
  '/bills/$id': typeof BillsIdRoute
  '/bills/create': typeof BillsCreateRoute
  '/bills/house-of-representatives': typeof BillsHouseOfRepresentativesRoute
  '/bills/oval-office': typeof BillsOvalOfficeRoute
  '/bills/senate': typeof BillsSenateRoute
  '/elections/campaign': typeof ElectionsCampaignRoute
  '/elections/president': typeof ElectionsPresidentRoute
  '/elections/senate': typeof ElectionsSenateRoute
  '/parties/$id': typeof PartiesIdRoute
  '/parties/create': typeof PartiesCreateRoute
  '/profile/$id': typeof ProfileIdRoute
  '/bank/': typeof BankIndexRoute
  '/bills/': typeof BillsIndexRoute
  '/parties/': typeof PartiesIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/bills/edit/$id': typeof BillsEditIdRoute
  '/parties/manage/$id': typeof PartiesManageIdRoute
  '/parties/merge/$id': typeof PartiesMergeIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/calendar'
    | '/feed'
    | '/login'
    | '/register'
    | '/search'
    | '/settings'
    | '/api/bill-advance'
    | '/api/bot'
    | '/api/game-advance'
    | '/api/hourly-advance'
    | '/bank/create'
    | '/bills/$id'
    | '/bills/create'
    | '/bills/house-of-representatives'
    | '/bills/oval-office'
    | '/bills/senate'
    | '/elections/campaign'
    | '/elections/president'
    | '/elections/senate'
    | '/parties/$id'
    | '/parties/create'
    | '/profile/$id'
    | '/bank'
    | '/bills'
    | '/parties'
    | '/profile'
    | '/bills/edit/$id'
    | '/parties/manage/$id'
    | '/parties/merge/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/calendar'
    | '/feed'
    | '/login'
    | '/register'
    | '/search'
    | '/settings'
    | '/api/bill-advance'
    | '/api/bot'
    | '/api/game-advance'
    | '/api/hourly-advance'
    | '/bank/create'
    | '/bills/$id'
    | '/bills/create'
    | '/bills/house-of-representatives'
    | '/bills/oval-office'
    | '/bills/senate'
    | '/elections/campaign'
    | '/elections/president'
    | '/elections/senate'
    | '/parties/$id'
    | '/parties/create'
    | '/profile/$id'
    | '/bank'
    | '/bills'
    | '/parties'
    | '/profile'
    | '/bills/edit/$id'
    | '/parties/manage/$id'
    | '/parties/merge/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/calendar'
    | '/feed'
    | '/login'
    | '/register'
    | '/search'
    | '/settings'
    | '/api/bill-advance'
    | '/api/bot'
    | '/api/game-advance'
    | '/api/hourly-advance'
    | '/bank/create'
    | '/bills/$id'
    | '/bills/create'
    | '/bills/house-of-representatives'
    | '/bills/oval-office'
    | '/bills/senate'
    | '/elections/campaign'
    | '/elections/president'
    | '/elections/senate'
    | '/parties/$id'
    | '/parties/create'
    | '/profile/$id'
    | '/bank/'
    | '/bills/'
    | '/parties/'
    | '/profile/'
    | '/bills/edit/$id'
    | '/parties/manage/$id'
    | '/parties/merge/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  CalendarRoute: typeof CalendarRoute
  FeedRoute: typeof FeedRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRoute
  ApiBillAdvanceRoute: typeof ApiBillAdvanceRoute
  ApiBotRoute: typeof ApiBotRoute
  ApiGameAdvanceRoute: typeof ApiGameAdvanceRoute
  ApiHourlyAdvanceRoute: typeof ApiHourlyAdvanceRoute
  BankCreateRoute: typeof BankCreateRoute
  BillsIdRoute: typeof BillsIdRoute
  BillsCreateRoute: typeof BillsCreateRoute
  BillsHouseOfRepresentativesRoute: typeof BillsHouseOfRepresentativesRoute
  BillsOvalOfficeRoute: typeof BillsOvalOfficeRoute
  BillsSenateRoute: typeof BillsSenateRoute
  ElectionsCampaignRoute: typeof ElectionsCampaignRoute
  ElectionsPresidentRoute: typeof ElectionsPresidentRoute
  ElectionsSenateRoute: typeof ElectionsSenateRoute
  PartiesIdRoute: typeof PartiesIdRoute
  PartiesCreateRoute: typeof PartiesCreateRoute
  ProfileIdRoute: typeof ProfileIdRoute
  BankIndexRoute: typeof BankIndexRoute
  BillsIndexRoute: typeof BillsIndexRoute
  PartiesIndexRoute: typeof PartiesIndexRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
  BillsEditIdRoute: typeof BillsEditIdRoute
  PartiesManageIdRoute: typeof PartiesManageIdRoute
  PartiesMergeIdRoute: typeof PartiesMergeIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed': {
      id: '/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof FeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/': {
      id: '/profile/'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parties/': {
      id: '/parties/'
      path: '/parties'
      fullPath: '/parties'
      preLoaderRoute: typeof PartiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bills/': {
      id: '/bills/'
      path: '/bills'
      fullPath: '/bills'
      preLoaderRoute: typeof BillsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bank/': {
      id: '/bank/'
      path: '/bank'
      fullPath: '/bank'
      preLoaderRoute: typeof BankIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$id': {
      id: '/profile/$id'
      path: '/profile/$id'
      fullPath: '/profile/$id'
      preLoaderRoute: typeof ProfileIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parties/create': {
      id: '/parties/create'
      path: '/parties/create'
      fullPath: '/parties/create'
      preLoaderRoute: typeof PartiesCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parties/$id': {
      id: '/parties/$id'
      path: '/parties/$id'
      fullPath: '/parties/$id'
      preLoaderRoute: typeof PartiesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/elections/senate': {
      id: '/elections/senate'
      path: '/elections/senate'
      fullPath: '/elections/senate'
      preLoaderRoute: typeof ElectionsSenateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/elections/president': {
      id: '/elections/president'
      path: '/elections/president'
      fullPath: '/elections/president'
      preLoaderRoute: typeof ElectionsPresidentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/elections/campaign': {
      id: '/elections/campaign'
      path: '/elections/campaign'
      fullPath: '/elections/campaign'
      preLoaderRoute: typeof ElectionsCampaignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bills/senate': {
      id: '/bills/senate'
      path: '/bills/senate'
      fullPath: '/bills/senate'
      preLoaderRoute: typeof BillsSenateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bills/oval-office': {
      id: '/bills/oval-office'
      path: '/bills/oval-office'
      fullPath: '/bills/oval-office'
      preLoaderRoute: typeof BillsOvalOfficeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bills/house-of-representatives': {
      id: '/bills/house-of-representatives'
      path: '/bills/house-of-representatives'
      fullPath: '/bills/house-of-representatives'
      preLoaderRoute: typeof BillsHouseOfRepresentativesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bills/create': {
      id: '/bills/create'
      path: '/bills/create'
      fullPath: '/bills/create'
      preLoaderRoute: typeof BillsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bills/$id': {
      id: '/bills/$id'
      path: '/bills/$id'
      fullPath: '/bills/$id'
      preLoaderRoute: typeof BillsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bank/create': {
      id: '/bank/create'
      path: '/bank/create'
      fullPath: '/bank/create'
      preLoaderRoute: typeof BankCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/hourly-advance': {
      id: '/api/hourly-advance'
      path: '/api/hourly-advance'
      fullPath: '/api/hourly-advance'
      preLoaderRoute: typeof ApiHourlyAdvanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/game-advance': {
      id: '/api/game-advance'
      path: '/api/game-advance'
      fullPath: '/api/game-advance'
      preLoaderRoute: typeof ApiGameAdvanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bot': {
      id: '/api/bot'
      path: '/api/bot'
      fullPath: '/api/bot'
      preLoaderRoute: typeof ApiBotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bill-advance': {
      id: '/api/bill-advance'
      path: '/api/bill-advance'
      fullPath: '/api/bill-advance'
      preLoaderRoute: typeof ApiBillAdvanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parties/merge/$id': {
      id: '/parties/merge/$id'
      path: '/parties/merge/$id'
      fullPath: '/parties/merge/$id'
      preLoaderRoute: typeof PartiesMergeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parties/manage/$id': {
      id: '/parties/manage/$id'
      path: '/parties/manage/$id'
      fullPath: '/parties/manage/$id'
      preLoaderRoute: typeof PartiesManageIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bills/edit/$id': {
      id: '/bills/edit/$id'
      path: '/bills/edit/$id'
      fullPath: '/bills/edit/$id'
      preLoaderRoute: typeof BillsEditIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  CalendarRoute: CalendarRoute,
  FeedRoute: FeedRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRoute,
  ApiBillAdvanceRoute: ApiBillAdvanceRoute,
  ApiBotRoute: ApiBotRoute,
  ApiGameAdvanceRoute: ApiGameAdvanceRoute,
  ApiHourlyAdvanceRoute: ApiHourlyAdvanceRoute,
  BankCreateRoute: BankCreateRoute,
  BillsIdRoute: BillsIdRoute,
  BillsCreateRoute: BillsCreateRoute,
  BillsHouseOfRepresentativesRoute: BillsHouseOfRepresentativesRoute,
  BillsOvalOfficeRoute: BillsOvalOfficeRoute,
  BillsSenateRoute: BillsSenateRoute,
  ElectionsCampaignRoute: ElectionsCampaignRoute,
  ElectionsPresidentRoute: ElectionsPresidentRoute,
  ElectionsSenateRoute: ElectionsSenateRoute,
  PartiesIdRoute: PartiesIdRoute,
  PartiesCreateRoute: PartiesCreateRoute,
  ProfileIdRoute: ProfileIdRoute,
  BankIndexRoute: BankIndexRoute,
  BillsIndexRoute: BillsIndexRoute,
  PartiesIndexRoute: PartiesIndexRoute,
  ProfileIndexRoute: ProfileIndexRoute,
  BillsEditIdRoute: BillsEditIdRoute,
  PartiesManageIdRoute: PartiesManageIdRoute,
  PartiesMergeIdRoute: PartiesMergeIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
