/* eslint-disable @typescript-eslint/no-explicit-any */

import {
  Star,
  Flag,
  Shield,
  Globe,
  Heart,
  Compass,
  Users,
  Leaf,
  Zap,
  Crown,
  Flame,
  MapPin,
  Trophy,
  CheckCircle,
  Cigarette,
  GraduationCap,
  MessageCircleWarning,
  Landmark,
  Frown,
  Smile,
  Gavel,
  Scale,
  Building,
  Banknote,
  BadgeCheck,
  Handshake,
  Hammer,
  Factory,
  Wrench,
  Shovel,
  Truck,
  Flower,
  Droplet,
  Mountain,
  Wind,
  Infinity,
  Book,
  Lightbulb,
  Palette,
  Atom,
  Lock,
  Key,
  Siren,
  Camera,
  Sparkles,
  Sun,
  Moon,
  Gem,
  Megaphone,
  Axe,
  Sword,
  Skull,
  Target,
  Eclipse,
  Languages,
  Orbit,
  RefreshCw,
  RefreshCcw,
} from "lucide-react";

export const icons: { name: string; Icon: any }[] = [
  { name: "Star", Icon: Star },
  { name: "Flag", Icon: Flag },
  { name: "Shield", Icon: Shield },
  { name: "Globe", Icon: Globe },
  { name: "Heart", Icon: Heart },
  { name: "Compass", Icon: Compass },
  { name: "Landmark", Icon: Landmark },
  { name: "Users", Icon: Users },
  { name: "Leaf", Icon: Leaf },
  { name: "Zap", Icon: Zap },
  { name: "Crown", Icon: Crown },
  { name: "Flame", Icon: Flame },
  { name: "MapPin", Icon: MapPin },
  { name: "Trophy", Icon: Trophy },
  { name: "CheckCircle", Icon: CheckCircle },
  { name: "GraduationCap", Icon: GraduationCap },
  { name: "MessageCircleWarning", Icon: MessageCircleWarning },
  { name: "Cigarette", Icon: Cigarette },
  { name: "Frown", Icon: Frown },
  { name: "Smile", Icon: Smile },

  // Added icons
  { name: "Gavel", Icon: Gavel },
  { name: "Scale", Icon: Scale },
  { name: "Building", Icon: Building },
  { name: "Banknote", Icon: Banknote },
  { name: "BadgeCheck", Icon: BadgeCheck },
  { name: "Handshake", Icon: Handshake },

  { name: "Hammer", Icon: Hammer },
  { name: "Factory", Icon: Factory },
  { name: "Wrench", Icon: Wrench },
  { name: "Shovel", Icon: Shovel },
  { name: "Truck", Icon: Truck },

  { name: "Flower", Icon: Flower },
  { name: "Droplet", Icon: Droplet },
  { name: "Mountain", Icon: Mountain },
  { name: "Wind", Icon: Wind },

  { name: "Infinity", Icon: Infinity },
  { name: "Book", Icon: Book },
  { name: "Lightbulb", Icon: Lightbulb },
  { name: "Palette", Icon: Palette },
  { name: "Atom", Icon: Atom },

  { name: "Lock", Icon: Lock },
  { name: "Key", Icon: Key },
  { name: "Siren", Icon: Siren },
  { name: "Camera", Icon: Camera },

  { name: "Sparkles", Icon: Sparkles },
  { name: "Sun", Icon: Sun },
  { name: "Moon", Icon: Moon },
  { name: "Gem", Icon: Gem },

  { name: "Megaphone", Icon: Megaphone },
  { name: "Axe", Icon: Axe },
  { name: "Sword", Icon: Sword },
  { name: "Skull", Icon: Skull },
  { name: "Target", Icon: Target },
  { name: "Eclipse", Icon: Eclipse },

  { name: "Languages", Icon: Languages },
  { name: "Orbit", Icon: Orbit },
  { name: "RefreshCw", Icon: RefreshCw },
  { name: "RefreshCcw", Icon: RefreshCcw },
];
