import {
  CheckCircle,
  Cigarette,
  Compass,
  Crown,
  Flag,
  Flame,
  Frown,
  Globe,
  GraduationCap,
  Heart,
  Landmark,
  Leaf,
  type LucideIcon,
  MapPin,
  MessageCircleWarning,
  Shield,
  Smile,
  Star,
  Trophy,
  Users,
  Zap,
} from "lucide-react";

export const icons: { name: string; Icon: LucideIcon }[] = [
  { name: "Star", Icon: Star },
  { name: "Flag", Icon: Flag },
  { name: "Shield", Icon: Shield },
  { name: "Globe", Icon: Globe },
  { name: "Heart", Icon: Heart },
  { name: "Compass", Icon: Compass },
  { name: "Landmark", Icon: Landmark },
  { name: "Users", Icon: Users },
  { name: "Leaf", Icon: Leaf },
  { name: "Zap", Icon: Zap },
  { name: "Crown", Icon: Crown },
  { name: "Flame", Icon: Flame },
  { name: "MapPin", Icon: MapPin },
  { name: "Trophy", Icon: Trophy },
  { name: "CheckCircle", Icon: CheckCircle },
  { name: "GraduationCap", Icon: GraduationCap },
  { name: "MessageCircleWarning", Icon: MessageCircleWarning },
  { name: "Cigarette", Icon: Cigarette },
  { name: "Frown", Icon: Frown },
  { name: "Smile", Icon: Smile },
];
